# Generated by Django 4.0.3 on 2022-09-29 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='email',
            field=models.OneToOneField(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('Evaluando', 'Evaluando'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Observado', 'Observado')], default='Evaluando', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='encargadoarea',
            name='email',
            field=models.OneToOneField(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
