# Generated by Django 4.0.3 on 2022-09-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0002_alter_administrador_email_alter_documento_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='data_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
